# Stage 1: Build Stage
FROM debian:buster AS builder
# Atualiza os pacotes e instala o Redis
RUN apt-get update && apt-get install -y redis-server
# Stage 2: Production Stage
FROM debian:buster
# Copia os binários do Redis do estágio de construção para o estágio de produção
COPY --from=builder /usr/bin/redis* /usr/bin/
# Define a variável de ambiente REDIS_HOST
ENV REDIS_HOST localhost
# Comando para iniciar o servidor Redis
CMD ["redis-server", "--bind", "0.0.0.0"]
