FROM debian:buster AS builder
RUN apt-get update && apt-get install -y redis-server
RUN apt-get install -y libatomic1

FROM debian:buster
COPY --from=builder /usr/bin/redis* /usr/bin/
ENV REDIS_HOST localhost
CMD ["redis-server", "--bind", "0.0.0.0"]
